"""
Proactive alerts router — pattern-matched alerts from new data.
"""

from fastapi import APIRouter

router = APIRouter()


@router.get("/")
async def get_alerts():
    """
    Return the list of proactive alerts generated by pattern matching
    new incidents against existing failure modes in the graph.
    """
    # TODO: Phase 7 — implement proactive alert feed
    return {"status": "not_implemented", "message": "Alerts endpoint — coming in Phase 7", "alerts": []}
