"""
Proactive alerts router — pattern-matched alerts from new data.
"""

from fastapi import APIRouter
from app.services.pattern_match import get_recent_alerts

router = APIRouter()


@router.get("/")
async def get_alerts():
    """
    Return the list of proactive alerts generated by pattern matching
    new incidents against existing failure modes in the graph.
    """
    alerts = get_recent_alerts()
    mapped_alerts = []
    for a in alerts:
        mapped_alerts.append({
            "title": f"Recurring Issue: {a.get('equipment_id')}",
            "timestamp": "Just now",
            "summary": a.get("message"),
            "severity": "critical"
        })
    return {
        "status": "success",
        "alerts": mapped_alerts
    }

