"""
Proactive alerts router — pattern-matched alerts from new data.
"""

from fastapi import APIRouter
from app.services.pattern_match import get_recent_alerts

router = APIRouter()


@router.get("/")
async def get_alerts():
    """
    Return the list of proactive alerts generated by pattern matching
    new incidents against existing failure modes in the graph.
    """
    alerts = get_recent_alerts()
    return {
        "status": "success",
        "alerts": alerts
    }
